variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: laravel
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: laravel
  DB_HOST: mysql

cache:
  paths:
    - backend/vendor/
    - frontend/node_modules/

stages:
  - test

.config:
  image: php:8.2-fpm
  services:
    - mysql:latest
  before_script:
    # Change to the backend directory
    - cd ./backend
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    # install composer dependencies
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    # Copy over example configuration.
    # Don't forget to set the database config in .env.example correctly
    - cp .env.example .env
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan config:cache
    # Run database migrations.
    - php artisan migrate:refresh --seed
    # Run database seed
    - php artisan db:seed

check:
  stage: test
  extends:
    - .config
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
