variables:
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_USER: laravel
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: laravel
  DB_HOST: mysql

cache:
  paths:
    - backend/vendor/
    - frontend/node_modules/

stages:
  - test

.config:
  image: php:8.2-fpm
  services:
    - mysql:latest
  before_script:
    # Change to the backend directory
    - cd ./backend
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
    # Install pcntl, zip and redis extensions
    - apt-get update && apt-get install -y libzip-dev zip
    - pecl install redis
    - docker-php-ext-enable redis
    - docker-php-ext-configure pcntl --enable-pcntl
    - docker-php-ext-install pcntl zip
    # Install MySQL driver
    - docker-php-ext-install pdo_mysql
    # install composer dependencies
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    # Copy over example configuration.
    # Don't forget to set the database config in .env.example correctly
    - cp .env.example .env
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan key:generate --env=testing
    - php artisan config:cache
    - php artisan config:cache --env=testing
    - chmod -R 755 .
    # Run database migrations.
    - php artisan migrate:fresh

check:
  stage: test
  extends:
    - .config
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never
