name: First pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_DATABASE: ecommerce
          MYSQL_ROOT_PASSWORD: admin
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping"

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/checkout@v4
      - name: Copy .env
        working-directory: backend
        run: cp .env.testing .env
      - name: Install Dependencies
        working-directory: backend
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        working-directory: backend
        run: php artisan key:generate
      - name: Directory permissions
        working-directory: backend
        run: chmod -R 777 storage bootstrap/cache
      - name: phpstan
        working-directory: backend
        run: vendor/bin/phpstan analyse --memory-limit=1G
      - name: phpinsights
        working-directory: backend
        run: |
          php artisan insights --no-interaction \
          --min-quality=90 --min-complexity=90 \
          --min-architecture=90 --min-style=90 \
          --ansi --format=github-action
      - name: Run tests
        working-directory: backend
        run: php artisan test